### ISSUE TITLE
Endre klasse Patient

### ISSUE THREAD

**Issue by hhamnnes** [Bratakstator/BetterMemory#86]
Ende klasse slik at den kan bruke de nye metodene

**Comment by Bratakstator** [comment]
Forslag om å ha CloseRelatives være tilknyttet Patient, også å ha CloseRelatives package-private slik at de kun kan accesseres via relevant pasient.

**Comment by Bratakstator** [comment]
Har endret noen variabler, splittet "name" til "firstName" og "surname".
Endret "patientId" fra å være av type int til String.
Lagt til en ArrayList som holder på objekt-typen "CloseRelative".
Lagt til en metode som tillater å legge til en "CloseRelative", metoden mottar fornavn og etternavn, oppretter så et objekt av type "CloseRelative" og legger den til i liste.

Med de "nye metodene" antar jeg dem som blir opprettet i Issue #87.
Disse nye metodene er i så fall ikke blitt definert enda og er følgelig ikke lagt med, lar denne issue forbli i "In Progress" for nå.

Laget tests og kjørt dem.
